package kz.yerek.aireply.data.secure

import android.content.Context
import android.content.SharedPreferences
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Keystore-backed storage for account access and refresh tokens.
 *
 * WHAT THIS GUARANTEES. The secret is encrypted with an AES-256/GCM key that
 * lives in the Android Keystore. That key is generated on the device, is not
 * exportable, and cannot be read by this app or any other — the app can only
 * ask the Keystore to use it. The ciphertext sits in an app-private
 * SharedPreferences file that is excluded from cloud backup and device
 * transfer, so a restore on another phone cannot produce a decryptable copy.
 * This is the same guarantee class as the iOS project's Keychain item with
 * `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly`.
 *
 * WHAT IT DOES NOT CLAIM. It is not a vault against someone holding the
 * unlocked device, and it is not protection against a rooted phone.
 *
 * WHY NOT androidx.security:security-crypto. `EncryptedSharedPreferences` does
 * exactly this, but the library has been stuck in alpha and is now deprecated,
 * and it pulls Tink in for the privilege. The ~120 lines below have no
 * dependency and no upgrade risk. That matters more than usual here: this code
 * is loaded inside an input method, where every class loaded is startup cost.
 *
 * The credential is never logged, never put in an error message, never written
 * to settings, and never held in a field — it is read at call time and dropped.
 */
class SecureCredentialStore(context: Context) {

    private val prefs: SharedPreferences =
        context.applicationContext.getSharedPreferences(NAME, Context.MODE_PRIVATE)

    fun removeLegacySecrets() {
        delete(KEY_API)
        delete(KEY_BACKEND_TOKEN)
    }

    // -------------------------------------------------------- account tokens

    /**
     * The signed-in session's token pair.
     *
     * Тіркелгі токендері де осы шифрланған қоймада — қарапайым prefs-те емес.
     *
     * The input method has to read these while the device is locked but in use,
     * and nothing here may survive a backup restored onto another phone.
     */
    fun accessToken(): String? = read(KEY_ACCESS_TOKEN)

    fun setAccessToken(value: String?): Boolean {
        val trimmed = value?.trim()
        if (trimmed.isNullOrEmpty()) return delete(KEY_ACCESS_TOKEN)
        return write(KEY_ACCESS_TOKEN, trimmed)
    }

    fun refreshToken(): String? = read(KEY_REFRESH_TOKEN)

    fun setRefreshToken(value: String?): Boolean {
        val trimmed = value?.trim()
        if (trimmed.isNullOrEmpty()) return delete(KEY_REFRESH_TOKEN)
        return write(KEY_REFRESH_TOKEN, trimmed)
    }

    /** Drops the whole session. Used by sign-out and by an unrecoverable 401. */
    fun clearAccountTokens() {
        delete(KEY_ACCESS_TOKEN)
        delete(KEY_REFRESH_TOKEN)
    }

    // ---------------------------------------------------------------- crypto

    private fun read(name: String): String? = runCatching {
        val stored = prefs.getString(name, null) ?: return null
        val blob = Base64.decode(stored, Base64.NO_WRAP)
        if (blob.size <= IV_LENGTH) return null

        val iv = blob.copyOfRange(0, IV_LENGTH)
        val cipherText = blob.copyOfRange(IV_LENGTH, blob.size)

        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(TAG_BITS, iv))
        String(cipher.doFinal(cipherText), Charsets.UTF_8).takeIf { it.isNotEmpty() }
    }.getOrNull()

    private fun write(name: String, value: String): Boolean = runCatching {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val cipherText = cipher.doFinal(value.toByteArray(Charsets.UTF_8))
        val blob = cipher.iv + cipherText
        prefs.edit()
            .putString(name, Base64.encodeToString(blob, Base64.NO_WRAP))
            .commit()
    }.getOrDefault(false)

    private fun delete(name: String): Boolean =
        runCatching { prefs.edit().remove(name).commit() }.getOrDefault(false)

    /**
     * The Keystore key, created on first use.
     *
     * `setRandomizedEncryptionRequired` is left at its default of true, so the
     * IV is generated by the Keystore for every encryption and is stored with
     * the ciphertext. Reusing an IV under GCM is a catastrophic failure, and
     * this is the setting that makes it impossible to get wrong here.
     */
    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                // The keyboard must be able to read this while the device is in
                // use but locked, exactly like the iOS item's after-first-unlock
                // accessibility, so no user authentication is required here.
                .setUserAuthenticationRequired(false)
                .build()
        )
        return generator.generateKey()
    }

    private companion object {
        const val NAME = "aireply_secure"
        const val PROVIDER = "AndroidKeyStore"
        const val KEY_ALIAS = "kz.yerek.aireply.credentials"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val IV_LENGTH = 12
        const val TAG_BITS = 128

        const val KEY_API = "openai.api.key"
        const val KEY_BACKEND_TOKEN = "backend.client.token"
        const val KEY_ACCESS_TOKEN = "account.access.token"
        const val KEY_REFRESH_TOKEN = "account.refresh.token"
    }
}
